### ISSUE TITLE
ProtocolHack Error

### ISSUE THREAD

**Issue by Kurimatzu** [InventivetalentDev/NickNamer#15]
## What steps will reproduce the problem?  
1. 
2. 
3. 

## What were you expecting to happen? What happened instead?  

The/nick Command function normally.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

NickNamer version 3.11.8
Author: inventivetalent

## What Spigot version are you using? *Type /version*  
This server is running DreamSpigotPlus version git-DreamSpigotPlus-549b970 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

(DreamSpigot = Modified jar.)
(ProtocolHack)

## What plugins are you using? *Type /plugins*  
Plugins (4): NametagEdit, PacketListenerApi, ProtocolLib, NickNamer

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

http://pastebin.com/jaYGcgcm

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No

**Comment by InventivetalentDev** [comment]
This doesn't seem like it's only a 1.7 issue, you're also using a spigot fork I've never heard of before.  
Since 1.7 isn't supported by spigot anymore, and we're already 3 versions ahead (1.10), I'm not going to add any more support for 1.7 versions, sorry.  
You can try one of the _really_ old NickNamer versions, which should still be compatible with 1.7 (Probably 2.x).
