### ISSUE TITLE
Name Change reload the world?

### ISSUE THREAD

**Issue by MrCosgrove1** [InventivetalentDev/NickNamer#21]
## What steps will reproduce the problem?  
1.  Switch your nickname a few times
2. 
3. 

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.12.1 the newest.
## What Spigot version are you using? *Type /version*  
git-spigot-9797151-301db84 MC: 1.10.2 Impelemnting API version 1.10.2 R0.1 Snapshoz
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Nope
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm using Bungeecord yes.
Here is my config:
http://pastebin.com/UM1a3KEv
For the Main Problem watch out this screen:
http://prntscr.com/bthhcc

**Comment by InventivetalentDev** [comment]
You haven't filled the 'what happened instead' part, so I don't have an exact idea what the issue is actually about. 
Guessing from the title, you're talking about the world unloading sometimes. That is an issue with the Minecraft client and has no reliable solution. Just press `F3+A` to reload the world, or disable _selfUpdate_ in the config.
