### ISSUE TITLE
Add support for not replacing names in players tab list

### ISSUE THREAD

**Issue by elFlashor** [InventivetalentDev/NickNamer#41]
## What steps will reproduce the problem?
1. Set yourself a nickname using /nicknamer [player] [nick]
2. Use the tab key to open the players list
## What were you expecting to happen? What happened instead?

Player's names get replaced by the nickname they have set. There is no option in the config.yml to disable this.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

3.12.3
## What Spigot version are you using? _Type /version_

1.10.2-R0.1-SNAPSHOT
## What plugins are you using? _Type /plugins_

Irrelevant.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No

**Comment by MrRiptide** [comment]
The plugins part of the bug report form is **not** irrelevant, it could explain what problems are happening.  For example, in your case, if you have some kind of tab list plugin, that may be pulling the name from elsewhere that this plugin isn't changing.  Also, ensure you are using PacketListenerAPI, otherwise this plugin will not work.
