### ISSUE TITLE
PlaceholderAPI Implementation

### ISSUE THREAD

**Issue by InventivetalentDev** [InventivetalentDev/NickNamer#78]
> Simple placeholders such as %is_disguised% which returns a Boolean if whether or not the player is disguised and %display_name% which returns the player’s disguised name (or returns their actual name if not disguised) would be wonderful!

**Comment by Th3Shadowbroker** [comment]
I found out that clip already created a [PAPI eCloud expansion](https://api.extendedclip.com/expansions/nicknamer/) back in 2017. However I pesonally think it would be better if the plugin provides its expansion by itself so it can be easily updated in the future and is already contained within the plugins jar-file. So I'll leave a PR in case you prefer a implemented solution instead of a eCloud expansion. 😄
